name: 📝 Blank Issue
description: Create a blank issue for anything that doesn't fit other categories
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Use this template when your issue doesn't fit into any of the other available templates.
        
        Please provide as much detail as possible to help us understand your concern.

  - type: textarea
    id: content
    attributes:
      label: Issue Description
      description: Describe your issue, request, or concern here
      placeholder: Please describe your issue in detail...
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, logs, or information that might be helpful
      placeholder: Any additional information that might be relevant...
