name: 🔒 Security Issue
description: Report a security vulnerability or concern
labels: [security]
body:
  - type: markdown
    attributes:
      value: |
        **⚠️ IMPORTANT: Do not report security vulnerabilities in public issues!**
        
        For security vulnerabilities, please report privately following our [Security Policy](https://github.com/pixo2000/voidcapes/blob/main/SECURITY.md).
        
        Use this template only for security-related questions, discussions about security practices, or other non-sensitive security topics.

  - type: checkboxes
    id: checklist
    attributes:
      label: "Checklist"
      options:
        - label: "This is NOT a security vulnerability report (I understand vulnerabilities should be reported privately)"
          required: true
        - label: "I made sure that there are *no existing issues* - [open](https://github.com/pixo2000/voidcapes/issues) or [closed](https://github.com/pixo2000/voidcapes/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to."
          required: true
        - label: "I have taken the time to fill in all the required details. I understand that the issue will be dismissed otherwise."
          required: true

  - type: dropdown
    id: security-type
    attributes:
      label: Security Topic Type
      description: What type of security topic is this?
      options:
        - Security best practices question
        - Security documentation improvement
        - Security policy discussion
        - Security tooling/configuration
        - Other security-related topic
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe your security-related question, suggestion, or concern
      placeholder: Please provide details about your security topic...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Any additional context that might be helpful
      placeholder: |
        - What specific aspect of security are you concerned about?
        - Are there any relevant security standards or best practices to consider?
        - Any other relevant information...

  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Any other relevant information, references, or documentation
