name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'microsoft'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/libs/*.jar
          name: VoidCapes v${{ steps.get_version.outputs.VERSION }}
          body: |
            ## VoidCapes v${{ steps.get_version.outputs.VERSION }}
            
            ### Changes
            See the commit history for detailed changes.
            
            ### Installation
            1. Install [Fabric Loader](https://fabricmc.net/use/)
            2. Download and install [Fabric API](https://modrinth.com/mod/fabric-api)
            3. Download the mod file from the assets below
            4. Place the mod file in your `mods` folder
            
            ### Requirements
            - Minecraft 1.21.8
            - Fabric Loader 0.17.0+
            - Fabric API
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-modrinth:
    runs-on: ubuntu-latest
    needs: release
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'microsoft'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Publish to Modrinth
        run: ./gradlew modrinth
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          MODRINTH_VERSION_TYPE: release
          MODRINTH_CHANGELOG_TEXT: |
            ## VoidCapes v${{ steps.get_version.outputs.VERSION }}
            
            ### Changes
            See the [GitHub release](https://github.com/pixo2000/voidcapes/releases/tag/v${{ steps.get_version.outputs.VERSION }}) for detailed changes.
            
            ### Installation
            1. Install [Fabric Loader](https://fabricmc.net/use/)
            2. Download and install [Fabric API](https://modrinth.com/mod/fabric-api)
            3. Download this mod
            4. Place the mod file in your `mods` folder
